### ISSUE TITLE
Add README with Standard format

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/pixelated_pattern#3]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager) to understand better.

**Comment by singh1114** [comment]
I'll do it.

**Comment by salman-bhai** [comment]
Go ahead @singh1114

**Comment by salman-bhai** [comment]
@singh1114 Kindly re-send your Pull-Request with updated links. Do **not copy paste** the exact same links used in the example link mentioned!

**Comment by singh1114** [comment]
You don't have contribution.md in this repo. Should I add that first.

**Comment by salman-bhai** [comment]
@singh1114 Create an issue and then send a Pull Request.

**Comment by singh1114** [comment]
I have already sent a PR.

**Comment by salman-bhai** [comment]
Merged #6
